version: "3"

networks:
  my-network:
    driver: bridge

services:
  php:
    container_name: php
    build:
      dockerfile: Dockerfile
      context: ./backend
      args:
        - UID=${UID}
        - GID=${GID}
    networks:
      - my-network
    volumes:
      - ./backend:/home/site

  nginx:
    container_name: nginx
    image: nginx:alpine3.20
    networks:
      - my-network
    volumes:
      - ./backend:/home/site
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "4430:443"
    depends_on:
      - mysql
      - php
      - minio

  mysql:
    container_name: mysql
    image: mysql:8.0
    networks:
      - my-network
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 33060:3306
    volumes:
      - ./db:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - my-network

  mailpit:
    container_name: mailpit
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - my-network

  minio:
    container_name: minio
    hostname: images.viblo.test
    image: minio/minio
    command: server /data --console-address ":9001" --address ":80"
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:80"
      - "9001:9001"
    networks:
      - my-network

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
    ports:
      - "7700:7700"
    networks:
      - my-network
    volumes:
      - ./meili_data:/meili_data

  nodejs:
    container_name: nodejs
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - my-network
    volumes:
      - ./frontend:/home/site
      - /home/site/node_modules
    entrypoint: npm run dev
